[project]
name = "ai-for-panchayats"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dpic",
    "duckdb>=1.5.5",
    "duckdb-engine>=0.17.0",
    "dvc[s3]>=3.67.1",
    "loguru>=0.7.3",
    "openpyxl>=3.1.5",
    "pandas>=3.0.3",
    "pandera>=0.31.1",
    "polars>=1.41.2",
    "pyarrow>=24.0.0",
    "sqlalchemy>=2.0.51",
]

[tool.uv.sources]
dpic = { git = "ssh://git@github.com/Data-Policy-and-Innovation-Centre/dpic-org.git", rev = "main" }

[tool.pytest.ini_options]
testpaths = ["tests"]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
    "nbstripout>=0.9.1",
    "pytest>=9.0.3",
    "ruff>=0.15.15",
]
